### ISSUE TITLE
Got a KeyError when attempting to run

### ISSUE THREAD

**Issue by lawik** [Etherhypnos/agent-nfs-a0labs#1]
Traceback (most recent call last):
  File "newrelic-nfs-agent/nfs-agent-a0labs-newrelic", line 155, in run
    self.get_component_from_csv(data)
  File "newrelic-nfs-agent/nfs-agent-a0labs-newrelic", line 115, in get_component_from_csv
    self.populateDeltaMetrics(self.agent_host, metrics, "Files/rename", "Operations", row['rename'])
KeyError: 'rename'

**Comment by ybriffa** [comment]
Hello,

Did you run it as a single user or as a sudo/root ?

You need the privileges to run the tool nfsstat to access and gather data around nfs.

Best,

**Comment by lawik** [comment]
I believe I tried both.

**Comment by ybriffa** [comment]
Is it possible to you to give me the output of the following command : 
nftsstat -l 

You might have to run it with the right privileges

**Comment by abhijitchaudhari1** [comment]
I think the command should be 
    nfsstat -l

not 
   nftsstat -l

and I got the same error

**Comment by abhijitchaudhari1** [comment]
The most probable  cause of this error is your NFS server has not came across any rename operation and thats why the nfsstat -l does not show the rename.

@lawik  Please share your nfsstat -l  command output,

And if possible remove all those parameters from the code that do not come in nfsstat -l output 

E.g Remove the line  

**self.populateDeltaMetrics(self.agent_host, metrics, "Files/rename", "Operations", row['rename'])**

if nfsstat -l does not show rename

**Comment by ybriffa** [comment]
I'm looking for it asap
